#include QMK_KEYBOARD_H


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(
 KC_ESC,   KC_Q,   KC_W,   KC_E,   KC_R,   KC_T,                                    KC_Y,   KC_U,   KC_I,   KC_O,   KC_P,KC_BSPC,
LCTL_T(KC_TAB),KC_A,KC_S,  KC_D,LT(3,KC_F),LT(4,KC_G),                              KC_H,   KC_J,   KC_K,   KC_L,RALT_T(KC_SCLN),RCTL_T(KC_QUOT),
KC_LSFT,LGUI_T(KC_Z),LALT_T(KC_X),KC_C,KC_V,LSFT_T(KC_B),                   RSFT_T(KC_N),   KC_M,KC_COMM, KC_DOT,RGUI_T(KC_SLSH),KC_RSFT,
         KC_WBAK,KC_WFWD,                                                                        KC_MPRV,KC_MNXT,
                           MO(1), KC_ENT,                                         KC_SPC,  MO(2),
                                         KC_LALT,KC_LCTL,        KC_MPLY,KC_MUTE,
                                           SH_OS,KC_CAPS,        KC_VOLU,KC_VOLD),
	[1] = LAYOUT(
_______,KC_PGUP,KC_HOME,  KC_UP, KC_END,KC_LCBR,                                 KC_RCBR,   KC_7,   KC_8,   KC_9,KC_PERC,KC_PSLS,
_______,KC_PGDN,KC_LEFT,KC_DOWN,KC_RGHT,KC_LBRC,                                 KC_RBRC,   KC_4,   KC_5,   KC_6,KC_PMNS,KC_PAST,
_______,_______,_______,LCTL(KC_LEFT),LCTL(KC_RGHT),KC_LPRN,                     KC_RPRN,   KC_1,   KC_2,   KC_3,KC_PLUS, KC_EQL,
           RESET,_______,                                                                           KC_0,KC_PDOT,
                         _______,_______,                                        _______,_______,
                                         _______,_______,        _______,_______,
                                         _______,_______,        _______,_______),
	[2] = LAYOUT(
 KC_GRV,  KC_F1,  KC_F2,  KC_F3,  KC_F4,  KC_F5,                                   KC_F6,  KC_F7,  KC_F8,  KC_F9, KC_F10, KC_DEL,
KC_TILD,KC_EXLM,  KC_AT,KC_HASH, KC_DLR,KC_PERC,                                 KC_CIRC,KC_AMPR,KC_ASTR,KC_MINS, KC_EQL,KC_BSLS,
_______, KC_F11, KC_F12,_______,_______,_______,                                 _______,_______,_______,KC_UNDS,KC_PLUS,KC_PIPE,
           RESET,_______,                                                                        _______,_______,
                         _______,_______,                                        _______,_______,
                                         _______,_______,        _______,_______,
                                         _______,_______,        _______,_______),
	[3] = LAYOUT(
_______,_______,_______,_______,_______,_______,                                 KC_PGUP,KC_HOME, KC_END, KC_INS,_______,_______,
_______,_______,_______,_______,_______,_______,                                 KC_LEFT,KC_DOWN,  KC_UP,KC_RGHT,_______,_______,
_______,_______,_______,_______,_______,_______,                                 KC_PGDN,LCTL(KC_LEFT),LCTL(KC_RGHT),_______,_______,_______,
         _______,_______,                                                                        _______,_______,
                         _______,_______,                                        _______,_______,
                                         _______,_______,        _______,_______,
                                         _______,_______,        _______,_______),
	[4] = LAYOUT(
_______,_______,_______,_______,_______,_______,                                 KC_WH_U,_______,KC_MS_U,_______,_______,_______,
_______,_______,_______,_______,_______,_______,                                 KC_WH_D,KC_MS_L,KC_MS_D,KC_MS_R,_______,_______,
_______,_______,_______,_______,_______,_______,                                 _______,KC_WH_L,KC_WH_R,_______,_______,_______,
         _______,_______,                                                                        _______,_______,
                         KC_BTN2,KC_BTN1,                                        KC_BTN1,KC_BTN2,
                                         _______,_______,        _______,_______,
                                         _______,_______,        _______,_______)
};

